### ISSUE TITLE
Generated .xmi files contain default values for generated class instances.

### ISSUE THREAD

**Issue by ArenBabikian** [viatra/VIATRA-Generator#13]
We use the .vsconfig file to generate models based on some constraints specified in a .vql file.  The generation works well and generates correct .png and .gml files (the models in these files satisfy the specified constraints). Yet the generated .xmi files only contain the default values for the attributes of the generated class instances and thus do not correspond to the supposedly corresponding .png and .gml files.

**Comment by ArenBabikian** [comment]
It seems like the .xmi file is not being written to, or is not being saved. Opening the .xmi file in a text editor shows that the class instances it contains are empty, i.e. they do not contain any attribute values. This is why they only contain default values for the attributes.

**Comment by imbur** [comment]
By taking a quick glimpse at the code, I concluded that this part is quite suspicious:
https://github.com/viatra/VIATRA-Generator/blob/master/Framework/hu.bme.mit.inf.dslreasoner.logic2ecore/src/hu/bme/mit/inf/dslreasoner/logic2ecore/Logic2Ecore.xtend#L73
It seems as if attributes were not yet supported.
