### ISSUE TITLE
Missing library

### ISSUE THREAD

**Issue by Antolin1** [viatra/VIATRA-Generator#47]
Dear all,
I am trying to generate models conforming to a metamodel using the ViatraSolver and I am obtaining the following error:
`Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/antolin/Escritorio/model-generation/projects/VIATRA-Generator/Solvers/ILP-Solver/hu.bme.mit.inf.dslreasoner.ilp.cbc/lib/libviatracbc.so: **libcoinasl.so.1**: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2659)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at hu.bme.mit.inf.dslreasoner.ilp.cbc.CbcSolver.loadNatives(CbcSolver.java:46)
	at hu.bme.mit.inf.dslreasoner.ilp.cbc.CbcSolver.solve(CbcSolver.java:20)`

What should I do?

**Comment by kris7t** [comment]
The `libviatracbc.so` library is JNI wrapper around [COIN-OR Cbc](https://github.com/coin-or/Cbc), which we use as an ILP and LP solver. See our paper [Automated Generation of Consistent Graph Models with Multiplicity Reasoning](https://doi.org/10.1109/TSE.2020.3025732) if you are interested in the details.

1. You can install _Cbc_ on your system (package is `coin-or-Cbc-devel` or something similar in [Arch, CentOS, Fedora, and others](https://pkgs.org/search/?q=coin-or-cbc) and `coinor-libcbc-dev` in [Debian derivatives](https://pkgs.org/search/?q=coinor-libcbc)). Be sure to install development headers (`-devel` or `-dev` if pacakged separately), as the next steps will require compiling code that depends on Cbc.
2. Make sure that you can compile JNI libraries on your system. This typically requires the corresponding `-devel` or `-dev` package of your JDK of choice, and a working C++ compiler (`g++`). VIATRA-Generator uses the [cmake](https://cmake.org/) build system, so install that (it's packaged in [most distributions](https://pkgs.org/search/?q=cmake)), too.
3. Go into the `Solvers/ILP-Solver/hu.bme.mit.inf.dslreasoner.ilp.cbc/cpp` directory, create and enter a new `build` subdirectory, then run `cmake` and `make`. This would look something like this:

```
cd Solvers/ILP-Solver/hu.bme.mit.inf.dslreasoner.ilp.cbc/cpp
mkdir -p build
cd build
cmake ..
make
```

This should install a newly compiled `libviatracbc.so` in `Solvers/ILP-Solver/hu.bme.mit.inf.dslreasoner.ilp.cbc/lib` dynamically linked with you Cbc installation.

For a recent paper, [Automated Generation of Consistent Models with Structural and Attribute Constraints](https://doi.org/10.1145/3365438.3410962), we created a virtual machine that contains VIATRA-Generator, Cbc, and an appropriately linked `libviatracbc.so`. You can download it from  [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3950552.svg)](https://doi.org/10.5281/zenodo.3950552).

Alternatively, you can set `"scopePropagator" = "basicTypeHierarchy"` in your `.vsconfig` files, which disables the ILP-based scope propagator. For domains with complex multiplicity constraits, this might decrease the performance of the generator, but will allow it to run without the Cbc dependency.

**Comment by Antolin1** [comment]
Thx for the answer :). Now, I am trying to use the virtual machine. When I run the familyTree case study (that is, package run, class FamilyTreeGen) I obtain this error: `UnsatisfiedLinkError: no libz3java in java.library.path : [viatra2logic/lib, com.microsoft.z3/lib, ... ]`

**Comment by kris7t** [comment]
I don't think the FamilyTreeGen is up to date -- we were using [run.RunGeneratorConfig](https://github.com/viatra/VIATRA-Generator/blob/master/Tests/MODELS2020-CaseStudies/case.study.pledge.run/src/run/RunGeneratorConfig.xtend) from `case.study.pledge.run` with the familyTree domain (`-d FamilyTree`) in the MODELS 2020 paper.

Please do keep in mind that the virtual machine doesn't have the latest version of VIATRA-Generator (it's just the state of the code we had when writing the paper). I worked a bit on linking with Z3 since then (and @ArenBabikian integrated the dReal SMT solver, too). Running `git pull` in the VM and rebuilding in Eclipse should bring it up to date, I think.

If you have any further questions, especially for using VIATRA-Generator in research, I think it'd be easiest to have a conference call (so we can show stuff around with screen sharing and like). Feel free to contact us at [marussy@mit.bme.hu](mailto:marussy@mit.bme.hu) or [semerath@mit.bme.hu](mailto:semerath@mit.bme.hu) (@OszkarSemerath). We're always interested in people using our tool in new projects and interesting applications!

**Comment by Antolin1** [comment]
Thx for your answer. I fixed the problem by defining the environment variable LD_LIBRARY_PATH and assigning it the path of the folder com.microsoft.z3/lib.
With respect to why I am using VIATRA. I am using it for research reasons. I read this [paper](https://dl.acm.org/doi/10.1145/2976767.2976786) and I want to extend it and assess how realistic a generator is by using machine learning techniques. To this end, I am selecting state-of-the-art generators (VIATRA, RandomEmf and this [one](https://github.com/atlanmod/mondo-atlzoo-benchmark/tree/master/fr.inria.atlanmod.instantiator)) and I am trying to generate models. 
It would be nice if you helped me to use the generator. I will type to one of these emails.

**Comment by Antolin1** [comment]
Thanks a lot for your help !!!!
